const names = [
  "Akame ga Kill!",
  "Akatsuki no Yona",
  "Ansatsu Kyoushitsu",
  "Ao Haru Ride",
  "Ao No Exorcist",
  "Attack On Titans",
  "Bakuman",
  "Berserk",
  "Black Clover",
  "Bleach",
  "Blue Lock",
  "Boku No Hero Academia",
  "Boku dake ga Inai Machi",
  "Boruto NNG",
  "Btooom!",
  "Burn The Witch",
  "Chainsaw Man",
  "Classroom of the Elite: Year 1",
  "Classroom of the Elite: Year 2",
  "Dead Tube",
  "Death Note",
  "Death Note Tokubetsu Yomikiri",
  "Death Note Tokubetsu-hen",
  "Detective Conan",
  "Devils Line",
  "Devils Line II [Gyakushuu]",
  "Dr. Stone Reboot: Byakuya",
  "Dr: Stone",
  "Dragon Ball",
  "Dragon Ball Super",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
  "Edens Zero",
  "Fairy Tail",
  "Fairy Tail 100 Years Quest",
  "Fairy Tail Zero",
  "Fire Force",
  "Fire Punch",
  "Fullmetal Alchemist",
  "Gleipnir",
  "Goblin Slayer",
  "Golden Kamuy",
  "Haikyuu!!",
  "High-School DxD",
  "Highschool of the Dead",
  "Horimiya",
  "Hunter x Hunter",
  "I Sold My Life For Ten Thousand Yen Per Year",
  "Ijiranaide, Nagatoro-san",
  "Jibaku Shounen Hanako-kun",
  "Jujutsu Kaisen",
  "Jujutsu Kaisen 0",
  "Kaguya-sama: Love is War",
  "Kaiju No. 8",
  "Kakegurui",
  "Kakegurui Midari",
  "Kakegurui Twin",
  "Kimetsu No Yaiba",
  "Kimi no Na wa",
  "Kingdom",
  "Kiseijuu",
  "Koe no Katachi",
  "Komi Can't Communicate",
  "Kuzumi-Kun Cant You Read the Room",
  "Made in Abyss",
  "Mairimashita, Senpai",
  "Mob Psycho 100",
  "Monster",
  "Mushoku Tensei: Isekai Ittara Honki Dasu",
  "Nanatsu no Taizai",
  "Naruto",
  "Naruto: Shippuuden",
  "New Game!",
  "Nisekoi",
  "No Game No Life",
  "Noragami",
  "One Piece",
  "One Punch Man",
  "Overlord",
  "Perfect World",
  "Platinum End",
  "Prison School",
  "Pumpkin Night",
  "Re:Zero kara Hajimeru Isekai Seikatsu",
  "Record Of Ragnarok",
  "Sakamoto Days",
  "Samurai 8 Hachimaruden",
  "Shigatsu wa Kimi no Uso",
  "Shokugeki no Souma",
  "Spy X Family",
  "Sword Art Online",
  "Tate No Yuusha No Nariagari",
  "Tensei shitara Slime Datta Ken",
  "The Four Knights of Apocalypse",
  "The Promised Neverland",
  "Tokyo Ghoul",
  "Tokyo Ghoul:re",
  "Tokyo Revengers",
  "Tonikaku Kawaii",
  "Vagabond",
  "Vinland Saga",
  "We Never Learn",
  "Wotaku ni Koi wa Muzukashii",
  "Yamada-kun to 7-nin no Majo",
  "Youjo Senki",
  "Zetman"
];

export { names }