const names = [
  "Sakamoto Days",
  "One Piece",
  "Fullmetal Alchemist",
  "Kingdom",
  "Haikyuu!!",
  "Akatsuki no Yona",
  "Hunter x Hunter",
  "Death Note",
  "Shigatsu wa Kimi no Uso",
  "Jibaku Shounen Hanako-kun",
  "Dragon Ball",
  "Bakuman.",
  "Wotaku ni Koi wa Muzukashii",
  "Detective Conan",
  "Tonikaku Kawaii",
  "Sword Art Online",
  "Naruto",
  "Naruto: Shippuuden",
  "No Game No Life",
  "Re:Zero kara Hajimeru Isekai Seikatsu",
  "Fairy Tail",
  "Shokugeki no Souma",
  "Mob Psycho 100",
  "Tate no Yuusha no Nariagari",
  "Overlord",
  "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
  "Highschool of the Dead",
  "Kakegurui",
  "Ao No Exorcist",
  "Attack On Titans",
  "Dr: Stone",
  "The Promised Neverland",
  "Samurai 8 Hachimaruden",
  "Kimetsu No Yaiba",
  "Mairimashita, Senpai",
  "Kuzumi-Kun Cant You Read the Room",
  "Burn The Witch",
  "I Sold My Life For Ten Thousand Yen Per Year",
  "Tokyo Ghoul",
  "Tokyo Ghoul:re",
  "Black Clover",
  "Boku No Hero Academia",
  "One Punch Man",
  "Jujutsu Kaisen",
  "Chainsaw Man",
  "The Four Knights of Apocalypse",
  "Boruto NNG",
  "Fairy Tail 100 Years Quest",
  "Dragon Ball Super",
  "Nanatsu no Taizai",
  "Noragami",
  "Edens Zero",
  "Record Of Ragnarok",
  "Tokyo Revengers",
  "Fire Force",
  "Komi Can't Communicate",
  "Made in Abyss",
  "Vinland Saga",
  "Platinum End",
  "Perfect World",
  "Tate No Yuusha No Nariagari",
  "Death Note Tokubetsu Yomikiri",
  "Golden Kamuy",
  "Vagabond",
  "Spy X Family",
  "Kaiju No. 8",
  "Horimiya",
  "Berserk",
  "Kiseijuu",
  "Fairy Tail Zero",
  "Monster",
  "Blue Lock",
  "Fire Punch",
  "Jujutsu Kaisen 0",
  "Pumpkin Night",
  "Kimi no Na wa",
  "Ao Haru Ride",
  "Koe no Katachi",
  "Zetman",
  "Dr. Stone Reboot: Byakuya",
  "Tate No Yuusha No Nariagari",
  "Sword Art Online",
  "Overlord",
  "One Piece",
  "Haikyuu!!",
  "Tonikaku Kawaii",
  "Sakamoto Days"
];

export { names }